name: Check CoreDNS releases

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check for new releases
        run: |
          COREDNS_VERSION=$(curl --silent "https://api.github.com/repos/coredns/coredns/releases/latest" | jq -r .tag_name)
          REPO_VERSION=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .name)
          if [ "$COREDNS_VERSION" == "$REPO_VERSION" ]; then
              echo "Repository release matches latest CoreDNS release"
              echo "new_release=false" >> $GITHUB_OUTPUT
              echo "tag=$TAG" >> $GITHUB_OUTPUT
          else
              echo "Repository release does not match latest CoreDNS release"
              echo "CoreDNS: $COREDNS_VERSION"
              echo "Repository: $REPO_VERSION"
              echo "new_release=true" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.new_release == 'true'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get latest CoreDNS release
        id: info
        run: |
          TAG=$(curl --silent "https://api.github.com/repos/coredns/coredns/releases/latest" | jq -r .tag_name | sed 's/^v//')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build binaries
        env:
          COREDNS_VERSION: ${{ needs.check.outputs.tag }}
        run: ./build.sh

      - name: Create release
        uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048  # v2.2.0
        with:
          name: ${{ needs.check.outputs.tag }}
          files: dist/*
