name: Check CoreDNS releases

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check for new releases
        run: ./check-version.sh

      - name: Set new_release=true
        if: failure()
        run: |
          echo "new_release=true" >> $GITHUB_OUTPUT

      - name: Set new_release=false
        if: success() || cancelled()
        run: |
          echo "new_release=false" >> $GITHUB_OUTPUT

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.new_release == 'true'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get latest CoreDNS release
        id: info
        run: |
          TAG=$(curl --silent "https://api.github.com/repos/coredns/coredns/releases/latest" | jq -r .tag_name | sed 's/^v//')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build binaries
        env:
          COREDNS_VERSION: ${{ steps.info.outputs.tag }}
        run: ./build.sh

      - name: Create release
        uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048  # v2.2.0
        with:
          name: v${{ github.event.inputs.tag }}
          files: dist/*
