name: Check CoreDNS releases

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    outputs:
      new_release: ${{ steps.check.outputs.new_release }}
      tag: ${{ steps.check.outputs.tag }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check for new releases
        id: check
        run: |
          COREDNS_VERSION=$(curl --silent "https://api.github.com/repos/coredns/coredns/releases/latest" | jq -r .tag_name)
          REPO_VERSION=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .name)
          if [ "$COREDNS_VERSION" == "$REPO_VERSION" ]; then
              echo "Repository release matches latest CoreDNS release"
              echo "new_release=false" >> $GITHUB_OUTPUT
          else
              echo "Repository release does not match latest CoreDNS release"
              echo "CoreDNS: $COREDNS_VERSION"
              echo "Repository: $REPO_VERSION"
              echo "new_release=true" >> $GITHUB_OUTPUT
              echo "tag=$COREDNS_VERSION" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.new_release == 'true'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build binaries
        env:
          COREDNS_VERSION: ${{ needs.check.outputs.tag }}
        run: ./build.sh

      - name: Create tag
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ needs.check.outputs.tag }}',
              sha: context.sha
            })

      - name: Create release
        uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048  # v2.2.0
        with:
          name: ${{ needs.check.outputs.tag }}
          tag_name: ${{ needs.check.outputs.tag }}
          files: dist/*
