name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag (e.g., v1.2.3)"
        default: "latest"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Build binaries
        id: build
        run: ./build.sh

      - name: Draft release
        uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048  # v2.2.0
        with:
          name: v${{ github.event.inputs.tag }}
          files: dist/*
